### ISSUE TITLE
How to get mocha in the search path of mocha-ui

### ISSUE THREAD

**Issue by lanwin** [paulpflug/mocha-ui#2]
When I open "mocha-ui" I get the following error: "sh: mocha: command not found". I think the problem is that mocha is not in the search path of mocha-ui. The question is how to get it there? Sidenote: I use node and mocha with NVM.

**Comment by paulpflug** [comment]
npm install -g mocha

"should" work. Nvm should have the global dir added to PATH. If it doesn't, 
you have to add it manually..

Am 5. November 2015 08:13:16 schrieb Steve Wagner notifications@github.com:

**Comment by lanwin** [comment]
Hmm, it dose not. I already did "npm install -g mocha" and can run mocha directly in iTerm2. I get this error even when I run atom via "atom ." from my test directory.

**Comment by paulpflug** [comment]
hey,
should be fixed with 0.1.6. Sorry it took so long.

**Comment by lanwin** [comment]
works! Thanks very much.

**Comment by lanwin** [comment]
Btw: Wouldn't it to prefer the mocha from local node_modules/.bin if available?

**Comment by paulpflug** [comment]
Hi again ;)

it is done, should use the local mocha with full path, so no PATH is needed. But keeps the global mocha as a fallback
(Only works on the first project folder, though)
