### ISSUE TITLE
    "/usr/bin/env: 'node': No such file or directory

### ISSUE THREAD

**Issue by erelsgl** [paulpflug/mocha-ui#7]
When I open the UI, I see the following message:

```
"/usr/bin/env: 'node': No such file or directory
```

and no tests are run.

Probably because on my system (Ubuntu) I have "nodejs".

How can I tell mocha-ui to run nodejs?

**Comment by paulpflug** [comment]
hey,

mocha-ui calls `./node_modules/.bin/mocha`
which has the (standard node) Shebang `#!/usr/bin/env node`

I think the recommended way is to remove nodejs (which is hopelessly outdated)
and use a version manager like [nvm](https://github.com/creationix/nvm) or [n](https://github.com/tj/n) to manage your node. [how to](http://stackoverflow.com/questions/20031849/how-can-i-find-my-node-js-files-in-linux-usr-bin-node-is-not-working/32740546#32740546)

If this is not possible, create a softlink in one of your bin folders which points `node -> nodejs`

``` sh
sudo ln -s "$(which nodejs)" /usr/bin/node
```

If this is not possible change the line in `./node_modules/.bin/mocha`
(I won't recommend that ;) )

**Comment by erelsgl** [comment]
OK, thanks!
